{% set name = "serf" %}
{% set version = "1.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.apache.org/dist/serf/serf-{{ version }}.tar.bz2
  sha256: be81ef08baa2516ecda76a77adf7def7bc3227eeb578b9a33b45f7b41dc064e6
  patches:
    - SConstruct.patch
    # Patches from Ubuntu:
    - 01-bucket-empty-list.patch
    - 02-python-3.patch
    - 03-openssl-111i.patch
    - 04-openssl-3.patch
    - 05-bio-ctrl.patch

build:
  number: 0
  # Mac OS X seems to have an issue in the upstream libapr
  # library where the package was generated thinking it had
  # access to <sys/types.h>, which I don't believe our current
  # clang compilers have
  #
  # Windows was failing to link against OpenSSL with the custom
  # cmake configuration here.
  #
  # Skipping both of these platforms for now.
  skip: true  # [osx or win]
  run_exports:
    - {{ pin_subpackage('serf', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake  # [win]
  host:
    - openssl
    - libapr
    - libaprutil
    - zlib
    - expat
    - scons
  run:
    - libapr
    - libaprutil

test:
  commands:
    - if not exist %LIBRARY_INC%\serf.h     exit 1  # [win]
    - if not exist %LIBRARY_BIN%\serf-1.dll exit 1  # [win]

    - test -f ${PREFIX}/include/serf-1/serf.h       # [unix]
    - test -f ${PREFIX}/lib/libserf-1${SHLIB_EXT}   # [unix]


about:
  home: https://serf.apache.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A high performance C-based HTTP client library
  doc_url: https://serf.apache.org/abi/timeline/serf/index.html
  dev_url: https://serf.apache.org/contribute

extra:
  recipe-maintainers:
    - scopatz
